version: "3.7"

services:
  iuliust-gitlab:

    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.iuliust.fr'
    container_name: iuliust-gitlab
    environment:
      LETSENCRYPT_HOST: gitlab.iuliust.fr
      LETSENCRYPT_ENABLE: "true"
      LETSENCRYPT_EMAIL: iuliust@gmail.com
    image: gitlab/gitlab-ee:nightly
    ports: 
      - '80:80'
      - '443:443'
      - '22:22'
    restart: always
    volumes:
      - ../volume_iuliust/gitlab/config:/etc/gitlab
      - ../volume_iuliust/gitlab/logs:/var/log/gitlab
      - ../volume_iuliust/gitlab/data:/var/opt/gitlab
  iuliust-jenkins:
    hostname: jenkins.iuliust.fr
    container_name: iuliust-jenkins
    image: gitlab/gitlab-ee:nightly
    ports: [ "7080:8080", "7050:50000" ]
    volumes:
      - ../volume_iuliust/jenkins:/var/jenkins_home
