version: "3.7"

services:
  iuliust-gitlab:
    container_name: iuliust-gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.iuliust.fr:6443'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 6022
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: gitlab.iuliust.fr
      LETSENCRYPT_HOST: gitlab.iuliust.fr
      LETSENCRYPT_EMAIL: iuliust@gmail.com
    image: gitlab/gitlab-ee:nightly
    hostname: 'gitlab.iuliust.fr'
    ports: 
      - '6080:80'
      - '6443:443'
      - '6022:22'
    restart: always
    volumes:
      - ../volume_iuliust/gitlab/config:/etc/gitlab
      - ../volume_iuliust/gitlab/logs:/var/log/gitlab
      - ../volume_iuliust/gitlab/data:/var/opt/gitlab
  iuliust-jenkins:
    hostname: jenkins.iuliust.fr
    container_name: iuliust-jenkins
    image: gitlab/gitlab-ee:nightly
    ports: [ "7080:8080", "7050:50000" ]
    volumes:
      - ../volume_iuliust/jenkins:/var/jenkins_home
# registry_external_url 'http://gitlab-registry.iuliust.fr'
# gitlab_rails['gitlab_shell_ssh_port'] = 6022
# letsencrypt['enable'] = true
# letsencrypt['contact_emails'] = ['iuliust@gmail.com'] 