version: "3.7"

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    network_mode: host
#    networks:
#      - priv
    hostname: 'gitlab.iuliust.fr'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.iuliust.fr:6080'
        gitlab_rails['gitlab_shell_ssh_port'] = 6022
    ports:
      - '6080:80'
      - '6443:443'
      - '6022:22'
    restart: always
    volumes:
      - ../volume_iuliust/gitlab/config:/etc/gitlab
      - ../volume_iuliust/gitlab/logs:/var/log/gitlab
      - ../volume_iuliust/gitlab/data:/var/opt/gitlab
  jenkins:
    hostname: jenkins.iuliust.fr
    networks:
      - priv
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - '49001:8080'
      - '50000:50000'
    volumes:
      - volume_jenkins:/var/jenkins_home
volumes:
    volume_jenkins:
networks:
    priv:
